enum Events {
  APP__SET_LOCALE = 'APP__SET_LOCALE',
  APP__STOP_LOADING = 'APP__STOP_LOADING',
  APP__START_LOADING = 'APP__START_LOADING',
  APP__CHANGE_LOCALE = 'APP__CHANGE_LOCALE',
  APP__SET_PAGE_ERROR = 'APP__SET_PAGE_ERROR',
  APP__CLEAR_PAGE_ERROR = 'APP__CLEAR_PAGE_ERROR',
  APP__SET_CURRENT_ROUTE = 'APP__SET_CURRENT_ROUTE',
}

export default Events;
