export const TODO_LIST__ADD_TODO = 'TODO_LIST__ADD_TODO';
export const TODO_LIST__ADD_TODOS = 'TODO_LIST__ADD_TODOS';
export const TODO_LIST__DELETE_TODO = 'TODO_LIST__DELETE_TODO';
export const TODO_LIST__TRIGGER_DONE_TODO = 'TODO_LIST__TRIGGER_DONE_TODO';
